mysite/urls.py
from django.conf.urls import url
from django.contrib import admin
from mysite.views import here, math, meta, welcome, get_c, set_c, session_S, login, index, logout, register
#from views import here
#mysite 是指子mysite
from restaurants.views import menu, list_restaurants, foods, comment
#import restaurants.views
#restaurants.views.menu

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^here/$', here),
    #\{1,2}代表匹配 1 or 2 個數字
    #小括號中的字->參數 (2~n+1)個參數 第1個參數為HttpRequest
    url(r'^(\d{1,2})/plus/(\d{1,2})/$', math),
    url(r'^menu/$', menu),
    url(r'^meta/$', meta),
    url(r'^welcome/$', welcome),
    url(r'^restaurants_list/$', list_restaurants),
    url(r'^foods/$', foods),
    url(r'^comment/(\d{1,5})/$', comment),
    url(r'^get_cookies/$', get_c),
    url(r'^set_cookies/$', set_c),
    url(r'^session/$', session_S),
    url(r'^accounts/login/$', login),
    url(r'^accounts/logout/$', logout),
    url(r'^accounts/register/$', register),
    url(r'^index/$', index),
]

restaurants/models.py
from django.db import models

# Create your models here.
class Restaurant(models.Model):
    name = models.CharField(max_length=20)
    phone_number = models.CharField(max_length=15)
    address = models.CharField(max_length=50, blank=True)

    def __str__(self):
        return self.name

class Food(models.Model):
    name = models.CharField(max_length=20)
    price = models.DecimalField(max_digits=3, decimal_places=0)
    comment = models.CharField(max_length=50, blank=True)
    is_spicy = models.BooleanField(default=False)
    restaurant = models.ForeignKey(Restaurant)

    def __str__(self):
        return self.name

class Comment(models.Model):
    content = models.CharField(max_length=255)
    visitor = models.CharField(max_length=255)
    email = models.CharField(max_length=255)
    date_time = models.DateTimeField()
    restaurant = models.ForeignKey(Restaurant)

    def __str__(self):
        return self.name
    
    class Meta:
        ordering = ['date_time']
        permissions = (                     #元組 包含多個元組
            ("can_comment", "Can comment"), #元組 包含兩個元素(codename, name)
        )

restaurants/forms.py
from django import forms

class CommentForm(forms.Form):
    visitor = forms.CharField(max_length=20)
    email = forms.EmailField(max_length=20, required=False, label='E-mail')#label設定標籤
    content = forms.CharField(max_length=200, widget=forms.Textarea())

    def clean_content(self):
        content = self.cleaned_data['content']
        if len(content) < 5:
            raise forms.ValidationError('字數不足')
        return content

restaurants/views.py
#-*- coding: utf-8 -*-
from django.http import HttpResponse, HttpResponseRedirect
#自動載入templates(failed)
#from django.template.loader import get_template
from django.utils import timezone
from django.shortcuts import render_to_response
from django import template
from restaurants.models import Restaurant, Food, Comment
from django.template import RequestContext
from restaurants.forms import CommentForm
from django.shortcuts import render
from django.contrib.auth.decorators import login_required, user_passes_test, permission_required

def user_can_comment(user):
    return user.is_authenticated and user.has_perm('restaurants.can_comment')


def menu(request):
#    food1 = {
#            'name' : '番茄炒蛋','price' : 60,'comment' : '好吃','is_spicy' : False}
#    food2 = {
#            'name' : '蒜泥白肉','price' : 100,'comment' : '人氣','is_spicy' : False}
#    foods = [food1, food2]
    path = request.path
    restaurants = Restaurant.objects.all()
    return render_to_response('menu.html', locals())

#@login_required
#@permission_required('restaurants.can_comment', login_url='/accounts/login/')
    #user_passes_test 自帶login_required
#@user_passes_test(user_can_comment, login_url='/accounts/login/')
def list_restaurants(request):
    restaurants = Restaurant.objects.all()
#   if request.user.has_perm('restaurants.can_comment'):
#       return HttpResponse('Have can_comment')
    return render(request, 'restaurants_list.html', locals())

def foods(request):
    if 'id' in request.GET and request.GET['id'] != '':
        r = Restaurant.objects.get(id=request.GET['id'])
        return render_to_response('foods.html', locals())
    else:
        return HttpResponseRedirect("/restaurants_list/")
#    return HttpResponse(r)


def comment (request, id):
    if id:
        r = Restaurant.objects.get(id=id)
    else:
        return HttpResponseRedirect("/restaurants_list/")
    #error = False
    #errors = []
    if request.POST:
        f = CommentForm(request.POST)
        if f.is_valid():
            visitor = f.cleaned_data['visitor']
            content = f.cleaned_data['content']
            email = f.cleaned_data['email']
            date_time = timezone.localtime(timezone.now())
            c = Comment.objects.create( 
                    visitor=visitor,
                    email=email,
                    content=content,
                    date_time=date_time,
                    restaurant=r )
            f = CommentForm(initial={'content':'無意見'})
        #error = any(not request.POST[k] for k in request.POST)
    else:
        f = CommentForm(initial={'content':'無意見'})
    return render(request, 'comments.html', locals())
"""
        if any(not request.POST[k] for k in request.POST):
            errors.append('*有空白欄位')
        if '@' not in email:
            #error = True
            errors.append('* email格式不正確')
        if not errors:
            Comment.objects.create(
                    visitor=visitor,
                    email=email,
                    content=content,
                    date_time=date_time,
                    restaurant=r
            )
            visitor = '' 
            email = ''
            content = ''
        f = CommentForm() """

restaurants/templates/comments.html
<!doctype html>
<html>
    <head>
        <title> Comments </title>
        <meta charset='utf-8'>
    </head>
    <body>
        <h2>{{ r.name }}的評價</h2>
        {% if r.comment_set.all %}
            <p>目前共有{{ r.comment_set.all|length }}條評價</p>
            <table>
                <tr>
                    <th>留言者</th>
                    <th>時間</th>
                    <th>評價</th>
                    <th>Email</th>
                </tr>
            {% for c in r.comment_set.all %}
                <tr>
                    <td> {{ c.visitor }} </td>
                    <td> {{ c.date_time | date:"F j, Y" }} </td>
                    <td> {{ c.content }} </td>
                    <td> {{ c.email }} </td>
                </tr>
            {% endfor %}
            </table>
        {% else %}
            <p>無評價</p>
        {% endif %}

        <br /><br />
        <!--error{% if error %}
        <p style="color:red;"> 輸入不完整 </p>
        {% endif %}-->
        <!--
        {% for e in errors %}
            <p style="color:red;">{{ e }}</p>
        {% endfor %}
        -->
        {% if f.errors %}
        <p style="color:red;"> 請依提示修復表單 </p>
        {% endif %}

        <form action="" method="post"> {% csrf_token %}
            <!--
            <table>
                <tr>
                    <td> <label for="visitor">留言者:</label> </td>
                    <td> <input id="visitor" type="text" name="visitor" value="{{ visitor }}"> </td>
                </tr>
                <tr>
                    <td> <label for="email">電子信箱:</label> </td>
                    <td> <input id="email" type="text" name="email" value="{{ email }}"> </td>
                </tr>
                <tr>
                    <td> <label for="content">評價:</label> </td>
                    <td> 
                        <textarea id="content" rows="10" cols="48" name="content">{{ content }}</textarea>
                    </td>
                </tr>
            </table>     
            -->
            <!--
            <table>
                {{ f.as_table }}
            </table>
            -->
            <table>
                <tr>
                    <th> <label for="id_visitor">留言者：</label> </th>
                    <td> {{ f.visitor }} </td>
                    <td> {{ f.visitor.errors }}</td>
                </tr>
                <tr>
                    <th> <label for="id_email">E-mail：</label> </th>
                    <td> {{ f.email }} </td>
                    <td> {{ f.email.errors }}</td>
                </tr>
                <tr>
                    <th> <label for="id_content">評價：</label> </th>
                    <td> {{ f.content }} </td>
                    <td style="color:red"> {{ f.content.errors }}</td>
                </tr>
            </table>
            <input type="hidden" name="ok" value="yes">
            <input type="submit" value="給予評價">
        </form>
    </body>
</html>

restaurants/templates/foods.html
<!doctype html>
<html>
    <head>
        <title> Menu </title>
        <meta charset='utf-8'>
    </head>
    <body>
		<h2>{{ r.name }}</h2>
		{% if r.food_set.all %}
            <p> 共有{{ r.food_set.all|length }}道 </p>
            <table class="table">
                <tr>
                    <th> 名稱</th>
                    <th> 價格</th>
                    <th> 說明</th>
                    <th> 辣？</th>
                </tr>
                {% for food in r.food_set.all %}
                    <tr>
                        <td> {{ food.name}} </td>
                        <td> {{ food.price}} </td>
                        <td> {{ food.comment }} </td>
                        <td> {% if food.is_spicy %} 辣 {% else %}
                                        不辣 {% endif %} </td>
                    </tr>
                {% endfor %}
            </table>
        {% else %}
                <p> Empty! </p>
        {% endif %}
    </body>
</html>

restaurants/templates/menu.html
<!doctype html>
{% load myfilters %}
<html>
    <head>
        <title> Menu </title>
        <meta charset='utf-8'>
	<link rel=stylesheet href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">
	<link rel=stylesheet href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap-theme.min.css">
	<style>
	    th { text-align: center; }
	    div.menus {
	    	text-align: center;
		padding: 40px 15px;
	    }
	</style>
    </head>
    <body>
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
	<div class="container">
	    <div class="navbar-header">
		<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
			<span class="sr-only">Toggle navigation</span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
		</button>
		<a class = "navbar-brand" href="#"> MySite </a>
	    </div>
	 </div>
    </nav>

    <div class="container">

	<div class="menus">
	<p>
	<div class="location">
    		現在位置{{ path }}
	</div>
        {% for r in restaurants %}
		<h2>{{ r.name }}</h2>
		{% if r.food_set.all %}
		<p> 共有{{ r.food_set.all|length }}道 </p>
		<table class="table">
			<tr>
			    <th> 名稱</th>
			    <th> 價格</th>
			    <th> 說明</th>
			    <th> 辣？</th>
			</tr>
			{% for food in r.food_set.all %}
			<tr>
				<td> {{ food.name}} </td>
				<td> {{ food.price}} </td>
				<td> {{ food.comment }} </td>
				<!--<td> {% if food.is_spicy %} 辣 {% else %}
                                不辣 {% endif %} </td>-->
                <td> {{ food.is_spicy|yes_no:"辣/不辣" }} </td>
                <!--過濾器-->
			</tr>
			{% endfor %}
		</table>
        	{% else %}
            		<p> Empty! </p>
        	{% endif %}
	{% endfor %}
	</div>
	</div>
	<script src="https://ajax.googleapis.com/ajex/libs/jquery/1.11.1/jquery.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
    </body>
</html>

restaurants/templates/menu_none_model.html
<!doctype html>
<html>
    <head>
        <title> Menu </title>
        <meta charset='utf-8'>
	<!--<link rel=stylesheet type="text/css" href="menu.css" / >-->
	<style>
	    table, th, td{
	    	border: 1px solid black;
	    }
    </head>
    <body>
        {% for food in foods %}
        {% comment %}
        <!--{% for food in foods reversed %} 倒轉 -->
        {% endcomment %}
        <h3>第{{ forloop.counter }}道食物</h3>
        <ul>
            <li> 名稱 : {{ food.name }}</li>
            <li> 價格 : {{ food.price }}</li>
            <li> 說明 : {{ food.comment }}</li>
            <li> 辣？ : {{ food.is_spicy }}</li>
        </ul>
        {% empty %}
            <p> Empty! </p>
        {% endfor %}
    </body>
</html>

restaurants/templates/restaurants_list.html
<!doctype html>
<html>
    <head>
        <title> Restaurants </title>
        <meta charset='utf-8'>
    </head>
    <body>
        <h2>餐廳列表</h2>
        <!--form<form action="/foods/" method="get">-->
        <table>
            <tr>
                <th>選取</th>
                <th>店名</th>
                <th>電話</th>
                <th>地址</th>
                {% if perms.restaurants.can_comment %}
                <th>評價</th>
                {% endif %}
            </tr>
            {% for r in restaurants %}
                <tr>
                    <!--form<td> <input type="radio" name="id" value="{{r.id}}"> </td>-->
                    <td> <a href="/foods/?id={{ r.id }}"> menu </a> </td>
                    <td> {{ r.name  }}</td>
                    <td> {{ r.phone_number  }}</td>
                    <td> {{ r.address  }}</td>
                    <td> <a href="/comment/{{ r.id }}/"> 評論 </a> </td>
                    {% if perms.restaurants.can_comment %}
                    <td> <a href="/comment/{{ r.id }}/"> comment</a> </td>
                    {% endif %}
                </tr>
            {% endfor %}
        </table>
        <!--form<input type="submit" value="觀看menu">-->
        <!--form</form>-->
    </body>
</html>